'use client';
import {useEffect,useState,useRef} from 'react';
import {Activity,LayoutDashboard,ClipboardList,History,Settings,Play,RefreshCw,Check,Clock,AlertTriangle,Mail,MessageSquare,X,UserRound,CheckCircle2,Info,Bell,Download,Search} from 'lucide-react';
const fmt=(n:any)=>n==null?'비교 보류':Math.round(n).toLocaleString('ko-KR');
const pct=(n:any)=>n==null?'보류':(n*100).toFixed(1)+'%';
const day=(d:string,n:number)=>new Date(Date.parse(d+'T00:00:00Z')+n*86400000).toISOString().slice(0,10);
function Badge({children,tone='neutral'}:any){return <span className={'badge '+tone}>{children}</span>}
function Chart({data}:any){if(!data.length)return <div className="chart-empty">추이 불러오는 중</div>;const W=740,H=230,L=65,R=35,T=18,B=35,max=Math.max(100,...data.flatMap((r:any)=>[r.count,r.simple||0,r.gbm||0]))*1.1,x=(i:number)=>L+i*(W-L-R)/Math.max(1,data.length-1),y=(v:number)=>T+(max-v)*(H-T-B)/max;return <div className="chart"><div className="legend"><span><i className="orange"/>공개 관측</span><span><i className="gray"/>단순 보정</span><span><i className="blue"/>GBM 추정</span></div><svg viewBox={`0 0 ${W} ${H}`} role="img" aria-label="현재 자료일까지 관측값과 모델 추정 비교">{[0,.5,1].map((v,i)=><g key={i}><line x1={L} x2={W-R} y1={y(max*v)} y2={y(max*v)} stroke="#e1e8ef"/><text x={L-10} y={y(max*v)+4} textAnchor="end" fill="#74899a" fontSize="13">{fmt(max*v)}</text></g>)}{[['simple','#8093a6','5 4'],['gbm','#3b83b7','2 4'],['count','#cd7527','']].map(([key,color,dash])=><polyline key={key} fill="none" stroke={color} strokeWidth={key==='count'?3:2} strokeDasharray={dash} points={data.map((r:any,i:number)=>r[key]!=null?`${x(i)},${y(r[key])}`:'').filter(Boolean).join(' ')}/>)}{[0,Math.floor((data.length-1)/2),data.length-1].map((i,k)=><text key={k} x={x(i)} y={H-8} fill="#74899a" fontSize="13" textAnchor={k===0?'start':k===2?'end':'middle'}>{data[i].date.slice(5)}</text>)}</svg></div>}
export default function Home(){
const [mode,M]=useState('replay'),[scenario,S]=useState('printing'),[state,U]=useState<any>(null),[tab,T]=useState('today'),[selected,Sel]=useState(''),[series,Ser]=useState<any[]>([]),[busy,B]=useState(false),[error,E]=useState(''),[toast,Toast]=useState(''),[popup,Pop]=useState<any>(null),[contact,C]=useState<any>(null),[confirm,Confirm]=useState(false),[settings,F]=useState<any>({}),[assign,A]=useState('교통정보 담당'),[cause,Cause]=useState('미확인'),[note,N]=useState(''),[search,Q]=useState(''),[filter,Filter]=useState('전체');
const ref=useRef<HTMLDialogElement>(null),loadId=useRef(0),seenLive=useRef(new Set<string>());const c=state?.cases.find((x:any)=>x.id===selected),sc=state?.scenarios.find((x:any)=>x.id===scenario);
function select(x:any){Sel(x.id);A(x.assignee==='미배정'?(state?.settings.owner||'교통정보 담당'):x.assignee);Cause(x.cause);N(x.note||'')}
function receive(d:any){U(d);F(d.settings)}
async function load(){const id=++loadId.current;B(true);E('');try{const r=await fetch(`/api/ops?mode=${mode}&scenario=${scenario}`),d:any=await r.json();if(!r.ok)throw Error(d.error);if(id!==loadId.current)return;receive(d);if(mode==='live'&&d.settings.popup){const fresh=d.cases.find((x:any)=>x.status==='확인 대기'&&x.firstDate===d.date&&!seenLive.current.has(x.id));if(fresh){seenLive.current.add(fresh.id);Pop(fresh)}}const f=d.cases.find((x:any)=>x.approach===d.scenarios.find((s:any)=>s.id===scenario)?.target)||d.cases[0];if(f){Sel(f.id);A(f.assignee==='미배정'?d.settings.owner:f.assignee);Cause(f.cause);N(f.note||'')}else Sel('')}catch(e:any){if(id===loadId.current)E(e.message)}finally{if(id===loadId.current)B(false)}}
useEffect(()=>{Pop(null);C(null);Sel('');Ser([]);load()},[mode,scenario]);
useEffect(()=>{if(!c){Ser([]);return}let alive=true;Ser([]);fetch(`/api/ops?mode=${mode}&scenario=${scenario}&series=${encodeURIComponent(c.approach)}`).then(r=>r.json()).then((d:any)=>{if(alive)Ser(d.series||[])});return()=>{alive=false}},[selected,state?.date]);
useEffect(()=>{if(mode!=='live'||!['today','cases'].includes(tab))return;const timer=setInterval(async()=>{if(busy||popup||contact)return;try{const r=await fetch('/api/ops?mode=live&scenario=live');const d:any=await r.json();if(!r.ok)throw Error(d.error);U(d);const fresh=d.cases.find((x:any)=>x.status==='확인 대기'&&x.firstDate===d.date&&!seenLive.current.has(x.id));if(fresh&&d.settings.popup){seenLive.current.add(fresh.id);Pop(fresh)}}catch(e:any){E(e.message)}},60000);return()=>clearInterval(timer)},[mode,busy,popup,contact,tab]);
useEffect(()=>{if(popup||contact){if(ref.current&&!ref.current.open)ref.current.showModal()}else ref.current?.close()},[popup,contact]);
useEffect(()=>{if(toast){const t=setTimeout(()=>Toast(''),5500);return()=>clearTimeout(t)}},[toast]);
async function act(action:string,extra:any={}){if(busy)return null;B(true);E('');try{const r=await fetch('/api/ops',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({mode,scenario,action,...extra})}),d:any=await r.json();if(!r.ok)throw Error(d.error);if(d.state)receive(d.state);if(d.draft){Pop(null);C({...d.draft,caseId:extra.caseId});Confirm(false)}if(action==='replay'||action==='collect'){const focus=d.state.cases.find((x:any)=>x.approach===sc?.target)||d.state.cases[0];if(focus){Sel(focus.id);A(focus.assignee==='미배정'?d.state.settings.owner:focus.assignee);Cause(focus.cause);N(focus.note||'')};const fresh=d.state.cases.find((x:any)=>x.approach===sc?.target&&d.newIds?.includes(x.id))||d.state.cases.find((x:any)=>d.newIds?.includes(x.id));if(fresh&&d.state.settings.popup)Pop(fresh);Toast(d.unchanged?'이미 점검한 자료입니다. 중복 업무를 만들지 않았습니다.':`점검 완료 · 새 후보 ${d.newCount||0}건 · 반복 경보는 기존 건에 반영`)}else if(d.message)Toast(d.message);else if(action==='reset'){Sel('');Toast('재생 사례의 업무 상태를 초기화했습니다.')}else if(action!=='draft')Toast('업무 기록을 저장했습니다.');return d}catch(e:any){E(e.message);return null}finally{B(false)}}
function csv(){const rows=[['방향','공개값','시작일','최근일','담당','상태','원인'],...state.cases.map((x:any)=>[x.approach,x.observed,x.firstDate,x.lastDate,x.assignee,x.status,x.cause])];const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\uFEFF'+rows.map(r=>r.map((v:any)=>'"'+String(v).replaceAll('"','""')+'"').join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'}));a.download=`점검목록_${state.date}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
const open=state?.cases.filter((x:any)=>!['종료','실제 통행 변화'].includes(x.status))||[],pending=open.filter((x:any)=>x.status==='확인 대기').length;const list=(state?.cases||[]).filter((x:any)=>(filter==='전체'||filter===x.status)&&(!search||x.approach.includes(search)||x.assignee.includes(search))).sort((a:any,b:any)=>Number(b.approach===sc?.target)-Number(a.approach===sc?.target)||a.approach.localeCompare(b.approach));const next=state?day(state.date,1):'',atEnd=mode==='replay'&&state?.date>=sc?.end;
return <div className="shell"><aside><div className="brand"><Activity size={24}/>교통량 점검 지원</div><p className="side-caption">천안시 업무 흐름 시연</p><nav>{[['today','오늘의 점검',LayoutDashboard],['cases','업무 목록',ClipboardList],['outbox','정비 연락 이력',Mail],['audit','처리 기록',History],['settings','수집·연락 설정',Settings]].map(([id,title,Icon]:any)=><button key={id} className={tab===id?'active':''} onClick={()=>T(id)}><Icon size={18}/>{title}{id==='today'&&pending>0&&<em>{pending}</em>}</button>)}</nav><div className="side-bottom"><UserRound size={17}/>{state?.settings.owner||'교통정보 담당'}<small>분석상 점검 후보<br/>외부 연락은 발송 시연</small></div></aside>
<main><header><div><p className="crumb">교통정보 업무 / 데이터 품질 검토</p><h1>{{today:'오늘의 데이터 점검',cases:'업무 목록',outbox:'정비 연락 이력',audit:'처리 기록',settings:'수집·연락 설정'}[tab]}</h1></div><div className="header-actions"><Badge tone={mode==='replay'?'blue':'green'}>{mode==='replay'?'과거 사례 재생':'실데이터'}</Badge><button className="iconbtn" aria-label="새로고침" onClick={load} disabled={busy}><RefreshCw className={busy?'spin':''}/></button></div></header>
<div className="controls"><div className="segments"><button className={mode==='replay'?'active':''} onClick={()=>M('replay')}>과거 사례</button><button className={mode==='live'?'active':''} onClick={()=>M('live')}>실데이터</button></div>{mode==='replay'?<><select aria-label="과거 사례" value={scenario} onChange={e=>S(e.target.value)}><option value="printing">인쇄창4 북 · 급락</option><option value="cityhall">시청4 서 · 저값 시작</option><option value="recovery">인쇄창4 북 · 회복</option></select><div className="date"><Clock size={16}/><b>{state?.date||'확인 중'}</b><span>자료 기준</span></div><button className="btn primary" disabled={busy||!state||atEnd} onClick={()=>act('replay',{date:next})}><Play size={15}/>{atEnd?'재생 완료':`${next?day(next,1).slice(5).replace('-','/'):'다음'} 오전 8시 재생`}</button><button className="textbtn" disabled={busy} onClick={()=>{if(window.confirm('이 재생 사례의 업무·연락 시연 기록을 초기화할까요?'))act('reset')}}>초기화</button></>:<><div className="date"><Clock size={16}/><b>매일 08:00</b><span>한국시간 · 전날 자료</span></div><button className="btn primary" disabled={busy||!state} onClick={()=>act('collect')}><RefreshCw size={15}/>지금 수집·점검</button></>}</div>
<div className="context"><Info size={15}/>{mode==='replay'?`실제 공식값을 당시 시점으로 재생 · 학습 마감 ${state?.model.trainedThrough||'확인 중'} · 이후 자료로 학습하지 않음`:`자료 기준 ${state?.date||'확인 중'} · 공개값의 이상과 장비 고장 원인은 구분합니다.`}</div>
{error&&<div className="error" role="alert"><AlertTriangle size={18}/>{error}<button aria-label="오류 닫기" onClick={()=>E('')}><X size={16}/></button></div>}{!state&&<div className="empty">업무 목록을 불러오는 중입니다.</div>}
{state&&['today','cases'].includes(tab)&&<>{tab==='today'&&<><div className="kpis">{[['확인할 점검 후보',pending,'담당 확인 전'],['정비 회신 대기',open.filter((x:any)=>x.status==='정비 확인 중').length,'연락 시연 포함'],['회복 관찰',open.filter((x:any)=>x.status==='회복 관찰').length,'종료 전 유지기간 확인'],['최근 점검 방향',state.runs[0]?.rows||0,state.date+' 완결일']].map(([label,val,sub],i)=><div key={i}><label>{label}</label><strong>{val}<small>{i===3?'방향':'건'}</small></strong><p>{sub}</p></div>)}</div><div className="summary"><CheckCircle2 size={20}/><div><b>{state.runs[0]?.displayAt} 기준 점검</b><span>반복 경보는 같은 업무에 누적합니다. 원본과 추정값을 분리해 표시합니다.</span></div><button className="textbtn" onClick={()=>T('audit')}>수집 기록</button></div></>}
<div className="workspace"><section className="queue"><div className="section-head"><h2>점검 업무 <small>{list.length}</small></h2><button className="iconbtn" aria-label="CSV 내려받기" onClick={csv}><Download size={18}/></button></div><div className="queue-controls"><div className="search"><Search size={16}/><input aria-label="방향 담당 검색" placeholder="방향 · 담당자 검색" value={search} onChange={e=>Q(e.target.value)}/></div><select aria-label="업무 필터" value={filter} onChange={e=>Filter(e.target.value)}>{['전체','확인 대기','검토 중','정비 확인 중','회복 관찰','종료','실제 통행 변화'].map(x=><option key={x}>{x}</option>)}</select></div><div className="case-list">{list.map((x:any)=><button key={x.id} className={'case '+(selected===x.id?'selected':'')} onClick={()=>select(x)}><div><b>{x.approach.replace('_',' ')}</b><Badge tone={x.status==='회복 관찰'?'green':x.status==='확인 대기'?'amber':'neutral'}>{x.status}</Badge></div><p>{x.severity} · {fmt(x.observed)}대 · {x.assignee}</p><small>{x.firstDate.slice(5)} 시작 · {x.repeatDays}일 경보 이력{x.approach===sc?.target&&<em>대표 사례</em>}</small></button>)}{!list.length&&<div className="empty"><CheckCircle2/><b>점검 후보가 없습니다</b><p>다음 자료일의 실제 관측값으로 점검하세요.</p></div>}</div><div className="queue-foot">같은 방향의 반복 경보는 새 업무로 생성하지 않습니다.</div></section>
<section className="detail">{!c?<div className="empty"><ClipboardList/><b>점검 업무를 선택하세요</b><p>관측 근거와 담당·연락 절차를 확인합니다.</p></div>:<><div className="detail-head"><div><p className="eyebrow">품질 확인 업무 · {c.id.slice(0,8).toUpperCase()} · 카메라 {state.meta[c.approach]?.cameraId||'ID 확인 전'}</p><h2>{c.approach.replace('_',' ')}</h2></div><Badge tone={c.status==='회복 관찰'?'green':'amber'}>{c.status}</Badge></div><div className="notice"><AlertTriangle size={16}/>{c.reason}. 실제 원인은 확인 전입니다.</div><div className="facts">{[['공개 관측값',fmt(c.observed)+'대'],['단순 보정 수준',fmt(c.simple)],['GBM 추정 수준',fmt(c.gbm)],['관측 / 단순 보정',pct(c.drop)]].map(([l,v],i)=><div key={i}><label>{l}</label><strong className={i===0?'orange':''}>{v}</strong></div>)}</div><Chart data={series}/><div className="evidence-foot"><span>현재 시점까지 표시 · 추정값은 실제 통행량의 정답이 아닙니다.</span><button className="textbtn" onClick={()=>Pop(c)}>판정 근거</button></div><div className="steps">{['검토','배정','정비 확인','회복','종료'].map((x,i)=><span key={x}><em>{i+1}</em>{x}</span>)}</div><div className="row"><label>업무 담당<input value={assign} onChange={e=>A(e.target.value)} maxLength={60}/></label><button className="btn secondary" disabled={busy} onClick={()=>act('assign',{caseId:c.id,assignee:assign})}><UserRound size={16}/>담당 배정</button></div><label>원인 분류<select value={cause} onChange={e=>Cause(e.target.value)}>{['미확인','장비·검지 설정','공개 전송·통신','공사·통행 변화','기타'].map(x=><option key={x}>{x}</option>)}</select></label><label>확인 근거·메모<textarea value={note} onChange={e=>N(e.target.value)} maxLength={1500} placeholder="통화 회신, 공사 확인, 내부값 대조 등 실제 확인한 근거를 기록하세요."/></label><div className="actionbar"><button className="btn secondary" disabled={busy} onClick={()=>act('cause',{caseId:c.id,cause,note})}><Check size={16}/>검토 기록 저장</button><div><button className="btn primary" disabled={busy||['종료','실제 통행 변화'].includes(c.status)} onClick={()=>act('draft',{caseId:c.id,channel:'email'})}><Mail size={16}/>정비 메일</button><button className="btn secondary" disabled={busy||['종료','실제 통행 변화'].includes(c.status)} onClick={()=>act('draft',{caseId:c.id,channel:'sms'})}><MessageSquare size={16}/>문자</button></div></div><div className="recovery"><CheckCircle2 size={19}/><div><b>회복 수준 {c.recoveryDays}일 관측</b><p>{state.settings.recoveryDays}일 유지와 원인 확인 근거를 갖춘 뒤 담당자가 종료합니다.</p></div><button className="btn secondary" disabled={busy||c.status==='종료'} onClick={()=>act('close',{caseId:c.id})}>검토 종료</button></div></>}</section></div></>}
{state&&tab==='outbox'&&<section className="panel"><div className="section-head"><h2>정비업체 연락 검토 이력</h2><Badge tone="blue">외부 발송 없음</Badge></div><p className="muted">실제 발송 제공사는 연결하지 않았습니다. 시나리오의 수신자·내용·담당 검토 이력을 저장합니다.</p>{!state.outbox.length?<div className="empty"><Mail/><b>아직 연락 이력이 없습니다</b></div>:state.outbox.map((o:any)=><article className="outbox" key={o.id}><div><Badge>{o.channel==='sms'?'문자':'메일'}</Badge><b>{o.approach.replace('_',' ')}</b><Badge tone="green">발송 시연 완료</Badge></div><p>{o.recipient} · {new Date(o.at).toLocaleString('ko-KR',{timeZone:'Asia/Seoul'})}</p><pre>{o.body}</pre><small>실제 외부 발송: 미발송</small></article>)}</section>}
{state&&tab==='audit'&&<section className="panel"><h2>데이터 점검과 업무 처리 기록</h2>{state.audit.map((a:any)=><article className="audit" key={a.id}><Activity size={19}/><div><b>{a.action}</b><p>{a.detail}</p><small>{a.dataDate} 자료 · {a.actor} · {new Date(a.at).toLocaleString('ko-KR',{timeZone:'Asia/Seoul'})}</small></div></article>)}</section>}
{state&&tab==='settings'&&<div className="settings-grid"><section className="panel"><h2>오전 8시 데이터 점검</h2><div className="clock"><Clock size={26}/><strong>08:00</strong><span>Asia/Seoul</span></div><div className="setting-note"><b>전날 완결 데이터를 조회합니다.</b><p>당일 부분 수집값을 제외하고 누락·불일치가 있으면 판정을 보류합니다. 이전 업무 목록은 유지합니다.</p></div><dl><dt>자료 기준일</dt><dd>{state.date}</dd><dt>학습 마감</dt><dd>{state.model.trainedThrough}</dd><dt>예약 상태</dt><dd>{mode==='live'?'Vercel 08시 예약 · 요금제별 시각 오차 가능':'과거 시점 수동 재생'}</dd></dl><p className="muted">반복 경보는 같은 건에 누적합니다. 담당 검토 없이 정비 통지를 자동 발송하지 않습니다.</p></section><section className="panel"><h2>담당 및 정비 연락처</h2><p className="muted">시연할 연락처를 입력하세요. 실제 메일·문자는 발송되지 않습니다.</p>{[['owner','업무 담당'],['vendorName','정비업체 담당'],['vendorEmail','메일 주소'],['vendorPhone','문자 수신 번호']].map(([k,l])=><label key={k}>{l}<input value={settings[k]||''} maxLength={120} onChange={e=>F({...settings,[k]:e.target.value})} placeholder={k==='vendorEmail'?'maintenance@example.invalid':''}/></label>)}<label className="checkbox"><input type="checkbox" checked={!!settings.popup} onChange={e=>F({...settings,popup:e.target.checked})}/>새 후보를 요약 팝업으로 안내</label><button className="btn primary" disabled={busy} onClick={()=>act('settings',{settings})}>설정 저장</button></section><section className="panel review"><h2>공무원 업무 관점의 설계</h2><div><article><b>알림 피로 줄이기</b><p>새 후보만 요약 안내하고 같은 방향의 반복 경보는 기존 건에 누적합니다.</p></article><article><b>원인 확인 후 연락</b><p>공사·설정·전송을 구분하고 담당자와 수신자를 검토한 뒤 연락합니다.</p></article><article><b>자동 종료 방지</b><p>회복 관측을 수리 완료로 바꾸지 않습니다. 원인 근거 없이 종료할 수 없습니다.</p></article></div></section></div>}
<footer>공식 공개 통계 기반 · 기관 운영 시스템과 미연결 · 수리 원인 미확인 <a href="https://www.data.go.kr/data/15160141/fileData.do" target="_blank" rel="noreferrer">자료 출처</a></footer></main>
{(popup||contact)&&<dialog ref={ref} onCancel={()=>{Pop(null);C(null)}}><button className="close" aria-label="팝업 닫기" onClick={()=>{Pop(null);C(null)}}><X size={21}/></button>{popup&&<><div className="popup-icon"><Bell size={25}/></div><p className="eyebrow">AI 분석 점검 · {day(popup.lastDate,1)} 08:00 · 카메라 {state.meta[popup.approach]?.cameraId||'ID 확인 전'}</p><h2>{popup.approach.replace('_',' ')}<br/>공개값 점검이 필요합니다</h2><p className="muted">{popup.reason}. 실제 원인은 확인 전이며 담당 검토가 필요합니다.</p><div className="popup-facts">{[['관측값',fmt(popup.observed)],['단순 보정',fmt(popup.simple)],['GBM 추정',fmt(popup.gbm)]].map(([l,v])=><div key={l}><label>{l}</label><strong>{v}</strong></div>)}</div><div className="setting-note"><b>먼저 확인할 항목</b><p>공사·통행 제한, 검지 설정, 내부 저장값과 공개 전송값의 차이를 확인하세요. 추정값만으로 고장 확정이나 통지를 하지 않습니다.</p></div><div className="modal-actions"><button className="btn secondary" onClick={()=>Pop(null)}>목록에 남기고 닫기</button><button className="btn primary" onClick={async()=>{select(popup);Pop(null);T('today');await act('ack',{caseId:popup.id})}}>확인 시작</button></div><small className="muted">반복 경보는 기존 건에 누적 · 실제 통지 미발송</small></>}{contact&&<><div className="popup-icon blue"><Mail size={25}/></div><p className="eyebrow">정비업체 연락 · {contact.channel==='sms'?'문자':'메일'}</p><h2>{confirm?'수신자와 내용을 확인하세요':'점검 요청 내용 검토'}</h2><div className="contact-notice">통지 시나리오입니다. 실제 메일·문자는 발송되지 않습니다.</div><label>수신자<input value={contact.recipient||'연락처 미설정'} readOnly/></label>{!contact.recipient&&<button className="textbtn" onClick={()=>{C(null);T('settings')}}>정비업체 연락처 설정</button>}{contact.channel==='email'&&<label>제목<input value={contact.subject} readOnly/></label>}<label>내용<textarea className="message" value={contact.body} onChange={e=>C({...contact,body:e.target.value})} maxLength={5000}/></label><div className="modal-actions"><button className="btn secondary" onClick={()=>C(null)}>취소</button>{!confirm?<button className="btn primary" disabled={!contact.recipient||busy} onClick={()=>Confirm(true)}>발송 전 확인</button>:<button className="btn primary" disabled={busy} onClick={async()=>{const r=await act('simulateSend',{caseId:contact.caseId,channel:contact.channel,body:contact.body,confirm:true});if(r){C(null);Confirm(false)}}}>통지 시연 완료</button>}</div></>}</dialog>}
{toast&&<div className="toast" role="status"><CheckCircle2 size={18}/>{toast}</div>}</div>
}
